language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - docker pull tray/dynamodb-local
  - docker run -i -t -d -name ddb tray/dynamodb-local -port 8000
  - docker ps -a
  - docker port ddb
script:
  - npm test