language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - docker pull tray/dynamodb-local
  - docker run -i -t -d --name ddb -p 8000:8000 tray/dynamodb-local -inMemory -port 8000
  - docker ps -a
  - docker port ddb
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - npm test
deploy:
  provider: script
  script: npm run package-deploy